#!/bin/bash
#
# Copyright 2015 ScaleDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#



### BEGIN INIT INFO
# Provides:          scaledb_slm
# Required-Start:    $local_fs $time $remote_fs scaledb_cas
# Required-Stop:     $remote_fs $time $local_fs scaledb_cas
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    mysql
# X-Stop-After:      mysql 
# Short-Description: ScaleDB SLM
# Description:       ScaleDB SLM
### END INIT INFO

#set -x
. /lib/lsb/init-functions

SCALEDB_HOME="/usr/sbin"
SCALEDB_BIN="/usr/bin"
SCALEDB_LOCK_DIR="/var/lock/scaledb"
SCALEDB_CONFIG_DIR="/etc/scaledb"
SCALEDB_SLM_CONFIG="${SCALEDB_CONFIG_DIR}/slm.cnf"

# Start the service ScaleDB SLM Server (ScaleDB Lock Manager)
start() {
	if [ `pgrep -f ${SCALEDB_HOME}/scaledb_slm | wc -l` -gt 0 ]
  then
		echo ScaleDB SLM is already running.
    exit 0
  fi

	if [ ! -f ${SCALEDB_SLM_CONFIG} ]
	then
		echo Missing SLM configuration file.
		exit 1
	fi

  echo Starting ScaleDB SLM server...
  if [ "`${SCALEDB_BIN}/slm_run -b ${SCALEDB_HOME} -f ${SCALEDB_SLM_CONFIG} -v | tail -1`"="Ok" ]
  then
    ### Create the lock file ###
    pgrep -f ${SCALEDB_HOME}/scaledb_slm > ${SCALEDB_LOCK_DIR}/scaledb_slm_started
    echo ScaleDB SLM server started.
  else
  	echo ERROR starting SLM Server.
	exit 1
  fi
}

# Stop the service ScaleDB SLM
stop() {
	if [ `pgrep -f ${SCALEDB_HOME}/scaledb_slm | wc -l` -eq 0 ]
	then
		echo It looks like ScaleDB SLM is not running.
		log_end_msg 0
	fi

	echo Stopping ScaleDB SLM server...
	pkill -o -x scaledb_slm

	if [ `pgrep -f ${SCALEDB_HOME}/scaledb_slm | wc -l` -gt 0 ]
	then
		echo ERROR stopping SLM Server.
		exit 1
	else
		cat ${SCALEDB_LOCK_DIR}/scaledb_slm_started > ${SCALEDB_LOCK_DIR}/scaledb_slm_stopped
		echo ScaleDB SLM Server stopped.
	fi
}

# Status of the ScaleDB SLM
status() {
  if [ `pgrep -f ${SCALEDB_HOME}/scaledb_slm | wc -l` -gt 0 ]
  then
    echo ScaleDB SLM is running.
  else
    echo ScaleDB SLM is not running.
  fi
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status scaledb_slm
        ;;
  restart|reload|condrestart|force-reload)
        stop
	sleep 2
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|force-reload|status}"
        exit 1
esac
exit 0
