#!/bin/bash
#
# Copyright 2015 ScaleDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#set -x
SCALEDB_HOME="/usr/sbin"
MARIADB_HOME="/usr/sbin"
MARIADB_BIN="/usr/bin"
SCALEDB_CONFIG_DIR="/etc/scaledb"
SCALEDB_LIB_DIR="/usr/lib/scaledb"
MARIADB_DATA_DIR="/var/lib/mysql"
SCALEDB_CONFIG="${MARIADB_DATA_DIR}/scaledb.cnf"
MARIADB_CONF_DIR="/etc/mysql"
MARIADB_CONF_FILE="${MARIADB_CONF_DIR}/my.cnf"
SCALEDB_LOCK_DIR="/var/lock/scaledb"

# Start the service MariaDB (known as mysqld)
start() {
  if [ `pgrep -f ${MARIADB_BIN}/mysqld_safe | wc -l` -gt 0 ]
	then
		echo MariaDB Server is already running.
		exit 3
	elif [ `pgrep -f ${MARIADB_HOME}/mysqld | wc -l` -gt 0 ]
	then
		echo MariaDB Server is already running.
		exit 3
	fi

  if [ ! -f ${SCALEDB_CONFIG} ]
	then
		echo Missing ScaleDB configuration file.
		exit 1
	fi

  echo Starting MariaDB Server...
  export LD_LIBRARY_PATH=${SCALEDB_LIB_DIR}
  ${MARIADB_BIN}/mysqld_safe --defaults-file=${MARIADB_CONF_FILE} > /dev/null &

	pgrep -f ${MARIADB_HOME}/mysqld > ${SCALEDB_LOCK_DIR}/scaledb_mariadb_started
  echo MariaDB Server started.
}

# Restart the service MariaDB (mysqld)
stop() {
  if [ `pgrep -f ${MARIADB_HOME}/mysqld | wc -l` -eq 0 ]
  then
    echo It looks like MariaDB Server is not running.
    exit 3
  fi

  echo Stopping MariaDB Server...
	/etc/init.d/mysql stop
	cat ${SCALEDB_LOCK_DIR}/scaledb_mariadb_started > ${SCALEDB_LOCK_DIR}/scaledb_mariadb_stopped
  echo MariaDB Server stopped.
}

# Status of MariaDB
status() {
  if [ `pgrep -f ${MARIADB_HOME}/mysqld | wc -l` -gt 0 ]
  then
    echo MariaDB Server is running.
  else
    echo MariaDB Server is not running.
  fi
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status scaledb_mariadb
        ;;
  restart|reload|condrestart)
        stop
	sleep 3
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
